### ISSUE TITLE
启动schedule报错

### ISSUE THREAD

**Issue by wuchenlv1988** [cocofree/azkaban_assistant#9]
[root@dev-cdh04 webapp]# cat schedule_web.log 
Traceback (most recent call last):
  File "router/schedule_router.py", line 69, in <module>
    server.bind(options.port)
  File "/usr/lib/python2.6/site-packages/tornado/tcpserver.py", line 158, in bind
    backlog=backlog)
  File "/usr/lib/python2.6/site-packages/tornado/netutil.py", line 69, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/usr/lib64/python2.6/socket.py", line 184, in __init__
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 97] Address family not supported by protocol

**Comment by cocofree** [comment]
这个错没见过，建议python升级到2.7再试下
